In [1]:
import torch

In [7]:
x = torch.rand(10, requires_grad=True)
y = torch.rand(10)
x

tensor([0.5071, 0.0517, 0.8545, 0.9682, 0.9545, 0.1567, 0.4453, 0.5561, 0.9983,
        0.8126], requires_grad=True)

In [8]:
(y**2).mean()

tensor(0.2732)

In [10]:
# at least 1 tensor has the required_grad
# the output of any computation will now be a tensor that has the grad func attached to it
# as long as the grad func attached to it, we can compute gradient
b = (x**2).mean()
b

tensor(0.5028, grad_fn=<MeanBackward0>)

In [11]:
b.backward()
# if we call backward multiple time, the result will just be sum of the gradients

In [17]:
# this is the gradient of x itself x.grad
print(x)
print(x / 10 * 2)
print(x.grad)

tensor([0.5071, 0.0517, 0.8545, 0.9682, 0.9545, 0.1567, 0.4453, 0.5561, 0.9983,
        0.8126], requires_grad=True)
tensor([0.1014, 0.0103, 0.1709, 0.1936, 0.1909, 0.0313, 0.0891, 0.1112, 0.1997,
        0.1625], grad_fn=<MulBackward0>)
tensor([0.1014, 0.0103, 0.1709, 0.1936, 0.1909, 0.0313, 0.0891, 0.1112, 0.1997,
        0.1625])


In [19]:
torch.cuda.memory_allocated()

0

In [30]:
x= torch.rand(2**20, requires_grad=True, device='cuda')
torch.cuda.max_memory_allocated() / 1024 / 1024

16.001953125

In [31]:
b = x
for _ in range(100):
    b = torch.relu(x)
torch.cuda.max_memory_allocated() / 1024 / 1024

20.001953125

In [32]:
b.sum().backward()
torch.cuda.max_memory_allocated() / 1024 / 1024

20.0029296875

In [33]:
x.grad

tensor([1., 1., 1.,  ..., 1., 1., 1.], device='cuda:0')