In [32]:
import torch


In [33]:
model = torch.nn.Linear(10, 1)

In [34]:
x = torch.randn(20, 10)
y = torch.randn(20, 1)
print(f'{x=}')
print(f'{y=}')

x=tensor([[ 0.0790, -0.2198,  0.6648,  1.0009, -0.0825,  3.3295,  0.1987,  0.4668,
         -1.5555, -0.3773],
        [-2.8235,  0.1702, -0.7286,  1.0118,  1.2626,  0.2024, -0.4130, -0.7129,
         -2.0155, -1.0843],
        [ 0.2030,  0.0189, -1.6412,  1.3562,  1.1972,  0.3893,  0.0040, -0.3367,
         -0.2796,  0.7355],
        [ 1.2833,  0.0755, -2.4818, -0.4916,  1.3276,  0.2886, -0.9449, -0.5213,
          0.0175, -1.0955],
        [-0.0385, -0.0769,  2.6433, -0.0529,  1.2493, -0.0567, -2.2564, -1.1174,
         -0.1055, -0.6689],
        [ 2.0106, -0.0133, -1.0841,  0.7458, -0.3332, -0.2201,  0.9818,  1.0895,
         -0.8687, -0.1477],
        [-0.9575, -1.0020,  0.0075, -2.2585, -0.6990, -1.1712,  0.1661, -0.2547,
         -0.5416,  1.0276],
        [ 0.4514, -0.5068, -0.6664, -0.7749, -1.0564,  0.2733,  1.0128, -0.8390,
          0.9935,  1.0491],
        [ 0.4897,  0.7662,  2.0122,  0.3423,  0.2106,  0.3157, -0.1454,  0.7351,
         -0.7485, -1.4482],
        [-0.1741,

In [35]:
pred_y = model(x)
print(pred_y)

tensor([[ 0.1033],
        [ 0.6147],
        [ 0.7860],
        [ 0.5080],
        [ 0.2105],
        [-0.2513],
        [-0.8349],
        [-0.2584],
        [-0.3359],
        [-0.1754],
        [-0.1505],
        [-0.6918],
        [ 0.8975],
        [-0.1665],
        [ 0.2933],
        [ 0.0246],
        [-0.3584],
        [ 0.3379],
        [ 0.0699],
        [ 0.2618]], grad_fn=<AddmmBackward0>)


In [36]:
#y, pred_y
loss = torch.nn.functional.mse_loss(pred_y, y)
print(loss)

tensor(1.2007, grad_fn=<MseLossBackward0>)


In [37]:
def mse_loss(pred_y, y):
    return torch.mean((pred_y - y) ** 2)
mse_loss(pred_y, y)

tensor(1.2007, grad_fn=<MeanBackward0>)

In [38]:
y = (torch.randn(20, 1) > 0).float()
print(y)

tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.]])


In [39]:
loss = torch.nn.functional.binary_cross_entropy_with_logits(pred_y, y)
print(loss)

tensor(0.8091, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)


In [40]:
#multi-class classification expect long as label
n_classes = 3
model = torch.nn.Linear(10, n_classes)
y = (torch.randn(20) > 0).long() + (torch.randn(20) > 0).long()
print(y)

tensor([0, 0, 0, 0, 1, 1, 2, 0, 0, 1, 2, 0, 0, 1, 0, 0, 0, 0, 1, 1])


In [41]:
pred_y = model(x)
loss = torch.nn.functional.cross_entropy(pred_y, y)
print(loss)

#

tensor(1.0546, grad_fn=<NllLossBackward0>)
