In [12]:
import torch
import torch.nn as nn
from torch import Tensor

In [8]:
model = nn.Linear(10, 1)

In [5]:
print(f"{model.weight}")
print(f"{model.bias}")

Parameter containing:
tensor([[ 0.0526, -0.2603, -0.2663, -0.2465,  0.2104, -0.0732, -0.0741, -0.0360,
          0.1114, -0.2275]], requires_grad=True)
Parameter containing:
tensor([0.2769], requires_grad=True)


In [9]:
x = torch.zeros(10)
model(x)

tensor([0.1685], grad_fn=<ViewBackward0>)

In [21]:
class LinearClassifier(torch.nn.Module):
    def __init__(self, input_dim, output_dim) -> None:
        super().__init__()
        self.fc = torch.nn.Linear(input_dim, output_dim)

    def forward(self, x) -> Tensor:
        return nn.functional.sigmoid(self.fc(x))


model = LinearClassifier(10, 1)
print(model)
print(model.fc.weight)
print(model.fc.bias)
x = torch.zeros(10)
print(model(x))

LinearClassifier(
  (fc): Linear(in_features=10, out_features=1, bias=True)
)
Parameter containing:
tensor([[-0.3097,  0.2713, -0.2837,  0.2717,  0.1321,  0.1599, -0.2992,  0.1218,
         -0.2987, -0.3124]], requires_grad=True)
Parameter containing:
tensor([0.2715], requires_grad=True)
tensor([0.5675], grad_fn=<SigmoidBackward0>)


In [22]:
x = torch.rand(100, 10)
model(x)

tensor([[0.5010],
        [0.5757],
        [0.5969],
        [0.5559],
        [0.5681],
        [0.5023],
        [0.4752],
        [0.4700],
        [0.5191],
        [0.5312],
        [0.5298],
        [0.5193],
        [0.5147],
        [0.5534],
        [0.6009],
        [0.4055],
        [0.4408],
        [0.5227],
        [0.6206],
        [0.4264],
        [0.4056],
        [0.4627],
        [0.5199],
        [0.5623],
        [0.4284],
        [0.4761],
        [0.3942],
        [0.4631],
        [0.4865],
        [0.4626],
        [0.4296],
        [0.4959],
        [0.5132],
        [0.3935],
        [0.6505],
        [0.4884],
        [0.4855],
        [0.4799],
        [0.5032],
        [0.4794],
        [0.5207],
        [0.5249],
        [0.4394],
        [0.4513],
        [0.4807],
        [0.4333],
        [0.5241],
        [0.4685],
        [0.5468],
        [0.5780],
        [0.5000],
        [0.5955],
        [0.4366],
        [0.4660],
        [0.5192],
        [0

In [23]:
class LinearClassifier(torch.nn.Module):
    def __init__(self, input_dim, n_classes) -> None:
        super().__init__()
        self.fc = torch.nn.Linear(input_dim, n_classes)

    def forward(self, x) -> Tensor:
        return nn.functional.softmax(self.fc(x), dim=-1)


model = LinearClassifier(10, 4)
print(model)
print(model.fc.weight)
print(model.fc.bias)
x = torch.ones(10)
print(model(x))

LinearClassifier(
  (fc): Linear(in_features=10, out_features=4, bias=True)
)
Parameter containing:
tensor([[ 0.1607,  0.0145, -0.0918,  0.1707,  0.1554, -0.1733,  0.2101,  0.2095,
         -0.0396, -0.2819],
        [ 0.2158, -0.2280,  0.1341,  0.1551,  0.2325,  0.2953,  0.0526,  0.2520,
          0.1604, -0.2480],
        [ 0.2747, -0.2214,  0.0460, -0.0340, -0.0589,  0.0882,  0.2284, -0.0333,
         -0.1731,  0.1065],
        [-0.2597, -0.2721, -0.0334, -0.1167, -0.3135, -0.2127, -0.1045,  0.1159,
          0.0360, -0.1985]], requires_grad=True)
Parameter containing:
tensor([0.1250, 0.0310, 0.2078, 0.3030], requires_grad=True)
tensor([0.2499, 0.4524, 0.2428, 0.0549], grad_fn=<SoftmaxBackward0>)


In [25]:
x = torch.rand(20, 10)
model(x).sum(dim=-1)

tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000], grad_fn=<SumBackward1>)

In [26]:
class LinearClassifier(torch.nn.Module):
    def __init__(self, input_dim, n_classes) -> None:
        super().__init__()
        self.fc = torch.nn.Linear(input_dim, n_classes)

    def forward(self, x) -> Tensor:
        return nn.functional.sigmoid(self.fc(x))


model = LinearClassifier(10, 4)
print(model)
print(model.fc.weight)
print(model.fc.bias)
x = torch.ones(10)
print(model(x))

LinearClassifier(
  (fc): Linear(in_features=10, out_features=4, bias=True)
)
Parameter containing:
tensor([[ 0.2540, -0.2552, -0.1604,  0.3067,  0.2253,  0.2440,  0.2161, -0.1679,
         -0.2981,  0.2688],
        [-0.2490, -0.0090,  0.2673,  0.2871,  0.2868, -0.1420, -0.1721,  0.1614,
         -0.3081,  0.1501],
        [-0.0934, -0.1267,  0.0692,  0.0745, -0.0306, -0.2158,  0.0563,  0.2694,
         -0.1208,  0.0156],
        [ 0.1400,  0.1124, -0.1596,  0.3005, -0.1770,  0.2546,  0.1004, -0.0791,
          0.2643, -0.0076]], requires_grad=True)
Parameter containing:
tensor([-0.0131, -0.0943, -0.1251,  0.0275], requires_grad=True)
tensor([0.6502, 0.5444, 0.4434, 0.6849], grad_fn=<SigmoidBackward0>)


In [27]:
x = torch.rand(20, 10)
model(x).sum(dim=-1)

tensor([2.2269, 2.2121, 2.0604, 2.2888, 2.1063, 1.9913, 2.2050, 2.0772, 2.1242,
        2.0577, 2.2180, 2.2210, 2.1193, 2.1943, 2.1203, 2.0955, 2.1737, 2.2020,
        1.9623, 2.0911], grad_fn=<SumBackward1>)