In [ ]:
import torch

/Users/hphan10/Dropbox/Documents/MSAI/Deep-Learning/.venv/lib/python3.12/site-packages/torch/_subclasses/functional_tensor.py:295: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


In [2]:
a = torch.rand([10])
a

tensor([0.8121, 0.8082, 0.8225, 0.5347, 0.6089, 0.7091, 0.3455, 0.8970, 0.1278,
        0.8527])

In [18]:
a[::3]

tensor([0.8121, 0.5347, 0.3455, 0.8527])

In [4]:
b = torch.rand(2, 3, 4)
b

tensor([[[0.6742, 0.6255, 0.4020, 0.1292],
         [0.2769, 0.2768, 0.9593, 0.1177],
         [0.8095, 0.1557, 0.4421, 0.0704]],

        [[0.9775, 0.2552, 0.0120, 0.6068],
         [0.7943, 0.4438, 0.4343, 0.7468],
         [0.8986, 0.4316, 0.3762, 0.6132]]])

In [6]:
values, _ = torch.max(b, dim=2)
values

tensor([[0.6742, 0.9593, 0.8095],
        [0.9775, 0.7943, 0.8986]])

In [12]:
c = torch.arange(10, dtype=torch.float32)
c

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [13]:
c[3] = 4
c[5] = 8
c[0] = 9
c

tensor([9., 1., 2., 4., 4., 8., 6., 7., 8., 9.])

In [14]:
torch.unique(c, sorted=True)

tensor([1., 2., 4., 6., 7., 8., 9.])

In [15]:
d = torch.rand(10)
d

tensor([0.0760, 0.5786, 0.5564, 0.6689, 0.3458, 0.1715, 0.5386, 0.1829, 0.5940,
        0.8520])

In [17]:
torch.where(d > 0.5, d, 0)

tensor([0.0000, 0.5786, 0.5564, 0.6689, 0.0000, 0.0000, 0.5386, 0.0000, 0.5940,
        0.8520])

In [19]:
e = torch.rand(2,4)
e

tensor([[0.7253, 0.8667, 0.8656, 0.0950],
        [0.1351, 0.9110, 0.7230, 0.0260]])

In [20]:
e.mT

tensor([[0.7253, 0.1351],
        [0.8667, 0.9110],
        [0.8656, 0.7230],
        [0.0950, 0.0260]])

In [21]:
torch.transpose(e, 0, 1)

tensor([[0.7253, 0.1351],
        [0.8667, 0.9110],
        [0.8656, 0.7230],
        [0.0950, 0.0260]])

In [31]:
f = torch.rand(4, 4)
f

tensor([[0.0561, 0.4149, 0.8361, 0.3802],
        [0.3591, 0.6788, 0.3867, 0.6812],
        [0.5129, 0.3352, 0.4490, 0.4133],
        [0.9794, 0.9821, 0.9541, 0.9819]])

In [32]:
torch.diagonal(f, 0)

tensor([0.0561, 0.6788, 0.4490, 0.9819])

In [48]:
torch.flip(f, [1])

tensor([[0.3802, 0.8361, 0.4149, 0.0561],
        [0.6812, 0.3867, 0.6788, 0.3591],
        [0.4133, 0.4490, 0.3352, 0.5129],
        [0.9819, 0.9541, 0.9821, 0.9794]])

In [49]:
torch.diagonal(torch.flip(f, [1]), 0)

tensor([0.3802, 0.3867, 0.3352, 0.9794])

In [52]:
g = torch.arange(10, dtype=torch.float32)
g

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [56]:
torch.cumsum(g, dim=0)

tensor([ 0.,  1.,  3.,  6., 10., 15., 21., 28., 36., 45.])

In [66]:
h = torch.rand(3, 4)
h

tensor([[0.5399, 0.6920, 0.2963, 0.4554],
        [0.2284, 0.3217, 0.4884, 0.4043],
        [0.7421, 0.5990, 0.6848, 0.2188]])

In [75]:
aa = torch.sum(h, dim=0)
aa

tensor([1.5104, 1.6128, 1.4695, 1.0784])

In [76]:
torch.sum(aa, dim=0)

tensor(5.6711)

In [80]:
cumsum_rows = torch.cumsum(h, dim=1)
cumsum_rows

tensor([[0.5399, 1.2319, 1.5282, 1.9836],
        [0.2284, 0.5501, 1.0385, 1.4428],
        [0.7421, 1.3411, 2.0259, 2.2447]])

In [81]:
torch.cumsum(cumsum_rows, dim=0)

tensor([[0.5399, 1.2319, 1.5282, 1.9836],
        [0.7683, 1.7820, 2.5667, 3.4264],
        [1.5104, 3.1231, 4.5926, 5.6711]])

In [79]:

# Example 2D tensor
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Compute the cumulative sum along rows
cumsum_rows = torch.cumsum(x, dim=1)

# Compute the cumulative sum along columns on the result of cumsum_rows
cumsum_2d = torch.cumsum(cumsum_rows, dim=0)

# For the (i, j)th element (e.g., i = 1, j = 2)
i, j = 1, 2
sum_up_to_ij = cumsum_2d[i, j]

print(f"Sum of elements up to ({i}, {j}): {sum_up_to_ij.item()}")

Sum of elements up to (1, 2): 21


In [94]:
h
torch.where(h < 0.5, torch.tensor(0, dtype=h.dtype), h)

tensor([[0.5399, 0.6920, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.7421, 0.5990, 0.6848, 0.0000]])

In [89]:
j = torch.rand(2, 4)
j

tensor([[0.0558, 0.3408, 0.8043, 0.1801],
        [0.5361, 0.6422, 0.9390, 0.7500]])

In [97]:
torch.nonzero(j < 0.7, as_tuple=False).T

tensor([[0, 0, 0, 1, 1],
        [0, 1, 3, 0, 1]])

In [104]:
a = torch.arange(10)
b = torch.arange(10)
a[2] = 5
a[4] = 1
b[4] = 2
b[1] = 6
print(a)
print(b)

tensor([0, 1, 5, 3, 1, 5, 6, 7, 8, 9])
tensor([0, 6, 2, 3, 2, 5, 6, 7, 8, 9])


In [111]:
torch.diff(torch.unique(torch.stack((a, b), dim=0), sorted=True))

tensor([1, 1, 1, 2, 1, 1, 1, 1])

In [121]:
x = torch.rand(4)
y = torch.rand(4)
print(x)
print(y)

tensor([0.6275, 0.1185, 0.2452, 0.8692])
tensor([0.3565, 0.0963, 0.6011, 0.2639])


In [124]:
c = torch.abs(x - y) < 1e-3
c

tensor([False, False, False, False])

In [127]:
torch.sum(torch.any(c, dim=0))

tensor(0)

In [143]:
inputs = [
            ([[1.0, 2.0, 3.0]], [0.0, 0.0, 1.0]),
            ([[-1.0, 0.0, 10.0]], [1.0, 1.0, 0.0]),
            ([[0.1, 0.2, 0.3, 0.4, 0.5]], [1.0, 1.0, 0.0, 0.0, 1.0]),
        ]

In [153]:
for i in inputs:
    print(torch.as_tensor(i[0]))
    print(torch.as_tensor(i[1]))

tensor([[1., 2., 3.]])
tensor([0., 0., 1.])
tensor([[-1.,  0., 10.]])
tensor([1., 1., 0.])
tensor([[0.1000, 0.2000, 0.3000, 0.4000, 0.5000]])
tensor([1., 1., 0., 0., 1.])


In [156]:
a[0]

tensor([[0.1000, 0.3000, 0.3000]])

In [157]:
torch.mean(a[0])

tensor(0.2333)

In [216]:
a = torch.as_tensor([[74.8000, 88.4000, 54.4000, 56.6000, 65.3000, 81.7000, 74.5000, 94.8000,
 72.7000, 81.6000],
[67.4000, 70.0000, 51.1000, 58.4000, 64.6000, 75.9000, 84.8000, 90.0000,
 58.0000, 64.1000]])
a

tensor([[74.8000, 88.4000, 54.4000, 56.6000, 65.3000, 81.7000, 74.5000, 94.8000,
         72.7000, 81.6000],
        [67.4000, 70.0000, 51.1000, 58.4000, 64.6000, 75.9000, 84.8000, 90.0000,
         58.0000, 64.1000]])

In [188]:
mean = torch.mean(a, dim=1)
mean

tensor([74.4800, 68.4300])

In [200]:
diff = torch.abs(a - mean.unsqueeze(1))
diff

tensor([[3.2001e-01, 1.3920e+01, 2.0080e+01, 1.7880e+01, 9.1800e+00, 7.2200e+00,
         2.0004e-02, 2.0320e+01, 1.7800e+00, 7.1200e+00],
        [1.0300e+00, 1.5700e+00, 1.7330e+01, 1.0030e+01, 3.8300e+00, 7.4700e+00,
         1.6370e+01, 2.1570e+01, 1.0430e+01, 4.3300e+00]])

In [204]:
max_indices = torch.argmax(diff, dim=1)
most_extreme_measurements = a[torch.arange(a.size(0)), max_indices]
most_extreme_measurements

tensor([94.8000, 90.0000])

In [209]:
max_indices.ndim

1

In [215]:
torch.gather(a, dim=1, index=max_indices.unsqueeze(1)).squeeze(1)

tensor([94.8000, 90.0000])

In [217]:
a[-1, :]

tensor([67.4000, 70.0000, 51.1000, 58.4000, 64.6000, 75.9000, 84.8000, 90.0000,
        58.0000, 64.1000])