In [1]:
import torch

/Users/hphan10/Dropbox/Documents/MSAI/Deep-Learning/.venv/lib/python3.12/site-packages/torch/_subclasses/functional_tensor.py:295: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


In [2]:
a = torch.tensor([1.0, 2, 3], dtype=torch.float32)
print(a)

tensor([1., 2., 3.])


In [3]:
b = torch.rand([3, 3, 3], dtype=torch.float32)
print(b)

tensor([[[0.1098, 0.7664, 0.1831],
         [0.9706, 0.1117, 0.0971],
         [0.3527, 0.4859, 0.1823]],

        [[0.9162, 0.4673, 0.1936],
         [0.9402, 0.9664, 0.5480],
         [0.0869, 0.5404, 0.7167]],

        [[0.8869, 0.5433, 0.2253],
         [0.3932, 0.1791, 0.0995],
         [0.9988, 0.7616, 0.0748]]])


In [17]:
from PIL import Image
import numpy as np

img = Image.open('cat.jpg')
c = torch.as_tensor(np.array(img)).float()
print(c.shape)
print(c.dtype)
print(c.ndim)

torch.Size([719, 720, 3])
torch.float32
3


In [24]:
a = torch.arange(10)
b = torch.ones(10)
print(f'{a = } ')
print(f'{b = }')
print(f'{ a ** (2*b) = }')


a = tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) 
b = tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
 a ** (2*b) = tensor([ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.])


In [25]:
a = torch.rand(4)
b = torch.rand(5)
print(a + b)

RuntimeError: The size of tensor a (4) must match the size of tensor b (5) at non-singleton dimension 0

In [27]:
a = torch.rand(1_000_000_000)
b = torch.rand(1_000_000_000)
c = a + b

In [28]:
%timeit c = a + b

645 ms ± 24.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [29]:
a_gpu = a.to('cuda')
b_gpu = b.to('cuda')
%timeit c_gpu = a_gpu + b_gpu

OutOfMemoryError: CUDA out of memory. Tried to allocate 3.73 GiB. GPU 0 has a total capacity of 10.88 GiB of which 2.32 GiB is free. Including non-PyTorch memory, this process has 7.59 GiB memory in use. Of the allocated memory 7.45 GiB is allocated by PyTorch, and 2.61 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

In [33]:
a = torch.arange(6)
print(a)
print(a.shape)
print(a.view(2,3))
print(a.reshape(2,3))

tensor([0, 1, 2, 3, 4, 5])
torch.Size([6])
tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [35]:
a = torch.rand(2, 3)
print(a)
print(a.mT)

tensor([[0.7177, 0.4978, 0.6596],
        [0.5476, 0.9416, 0.3792]])
tensor([[0.7177, 0.5476],
        [0.4978, 0.9416],
        [0.6596, 0.3792]])


In [39]:
a = torch.rand(2, 3, 4)
print(a)
print()
print(a.permute(1, 2, 0).shape)

tensor([[[0.7171, 0.6878, 0.3559, 0.1472],
         [0.4094, 0.6893, 0.5885, 0.1162],
         [0.7918, 0.1962, 0.3687, 0.5836]],

        [[0.4939, 0.4533, 0.5442, 0.6519],
         [0.3762, 0.3699, 0.0762, 0.7861],
         [0.4480, 0.3796, 0.2892, 0.2823]]])

torch.Size([3, 4, 2])


In [44]:
a = torch.arange(6).view(3, 2, 1, 1)
print(a)


tensor([[[[0]],

         [[1]]],


        [[[2]],

         [[3]]],


        [[[4]],

         [[5]]]])


In [50]:
a = torch.arange(4).view(4,1)
b = torch.arange(5).view(1,5)*10

print(f'{a = }')
print(f'{b = }')
print(a * b)


a = tensor([[0],
        [1],
        [2],
        [3]])
b = tensor([[ 0, 10, 20, 30, 40]])
tensor([[  0,   0,   0,   0,   0],
        [  0,  10,  20,  30,  40],
        [  0,  20,  40,  60,  80],
        [  0,  30,  60,  90, 120]])


In [52]:
x = torch.randn(10, 2)
d = torch.zeros(10, 10)
for i in range(10):
    for j in range(10):
        d[i, j] = (x[i] - x[j]).pow(2).sum()

# compact
d = (x[:, None, :] - x[None, :, :]).pow(2).sum()

tensor([[0.0000e+00, 4.1248e+00, 1.0407e+00, 2.6010e+00, 3.2924e+00, 4.2008e+00,
         1.7571e+00, 2.4624e+00, 1.0985e+00, 3.9349e-01],
        [4.1248e+00, 0.0000e+00, 1.1017e+00, 5.7617e-01, 1.1484e+00, 1.2552e+01,
         1.7079e+00, 7.0066e-01, 4.1698e+00, 4.7723e+00],
        [1.0407e+00, 1.1017e+00, 0.0000e+00, 3.9068e-01, 8.6448e-01, 6.6194e+00,
         1.0755e+00, 3.6330e-01, 1.2153e+00, 1.3104e+00],
        [2.6010e+00, 5.7617e-01, 3.9068e-01, 0.0000e+00, 1.5964e-01, 7.9896e+00,
         2.1773e+00, 6.3169e-03, 1.7854e+00, 2.4900e+00],
        [3.2924e+00, 1.1484e+00, 8.6448e-01, 1.5964e-01, 0.0000e+00, 7.3348e+00,
         3.4758e+00, 1.3306e-01, 1.6523e+00, 2.6877e+00],
        [4.2008e+00, 1.2552e+01, 6.6194e+00, 7.9896e+00, 7.3348e+00, 0.0000e+00,
         1.1054e+01, 7.5535e+00, 2.2527e+00, 2.2598e+00],
        [1.7571e+00, 1.7079e+00, 1.0755e+00, 2.1773e+00, 3.4758e+00, 1.1054e+01,
         0.0000e+00, 2.2490e+00, 4.0231e+00, 3.3244e+00],
        [2.4624e+00, 7.0066

In [65]:
x = torch.randn(10, 2)
d = torch.zeros(10, 10)
max_dist, max_idx  = 0, (-1, -1)
for i in range(10):
    for j in range(10):
        if (x[i] - x[j]).pow(2).sum() > max_dist:
           max_dist, max_idx = (x[i] - x[j]).pow(2).sum(), (i, j)
print(max_dist, max_idx)
# compact
d = (x[:, None, :] - x[None, :, :]).pow(2).sum(-1)
print(d.max(), (d.argmax() // 10, d.argmax() % 10))

tensor(18.1639) (1, 8)
tensor(18.1639) (tensor(1), tensor(8))


In [68]:
a = torch.rand(2, 4)
b = torch.rand(4, 3)
c = a @ b
c.shape

torch.Size([2, 3])